In [2]:
import sys
import os

In [3]:
sys.path.append(
    os.path.abspath('..')
)

In [4]:
from src.team_strength import *

In [5]:
team_profiles_df = build_team_profiles()

In [6]:
team_profiles_df.head(20)

,team,matches_played,wins,draws,losses,win_pct,avg_goals_scored,avg_goals_conceded,avg_opponent_elo,elite_wins,world_cup_upsets,big_match_points,adjusted_strength
77,France,111,71,22,18,0.639640,2.081081,0.855856,1711.279279,22,4,262,429.673139
82,Spain,107,65,30,12,0.607477,2.317757,0.785047,1716.383178,14,0,175,407.683405
150,Belgium,105,66,19,20,0.628571,2.323810,0.819048,1655.895238,8,3,133,385.841936
90,Argentina,106,72,19,15,0.679245,1.990566,0.603774,1712.584906,7,1,129,379.101842
91,Japan,112,71,16,25,0.633929,2.276786,0.767857,1647.937500,5,2,94,372.465484
94,England,110,69,20,21,0.627273,2.145455,0.645455,1648.300000,9,0,87,362.955101
104,Brazil,104,64,22,18,0.615385,1.942308,0.644231,1741.038462,6,0,114,353.931179
101,Portugal,105,63,23,19,0.600000,2.219048,0.800000,1682.866667,6,0,79,348.563559
93,Netherlands,100,56,24,20,0.560000,2.200000,0.940000,1702.250000,7,0,98,336.525358
110,Morocco,119,78,26,15,0.655462,1.815126,0.512605,1597.378151,3,2,49,331.455514
40,Algeria,113,72,25,16,0.637168,2.061947,0.743363,1566.530973,1,0,19,316.480492
89,Italy,97,57,23,17,0.587629,1.938144,0.896907,1713.164948,7,0,84,311.693463
22,Iran,94,61,15,18,0.648936,2.010638,0.680851,1593.276596,0,0,7,301.279844
81,Germany,102,52,24,26,0.509804,2.137255,1.166667,1710.705882,8,0,82,301.136336
6,Denmark,100,54,26,20,0.540000,1.840000,0.820000,1678.840000,4,0,55,287.663785
107,Senegal,112,68,27,17,0.607143,1.651786,0.642857,1588.125000,2,0,31,285.760464
12,South Korea,113,62,27,24,0.548673,1.725664,0.858407,1619.460177,2,2,58,282.260327
98,Croatia,107,53,25,29,0.495327,1.654206,1.130841,1725.495327,7,2,118,276.535597
68,Austria,95,53,14,28,0.557895,1.747368,0.957895,1628.642105,5,0,74,276.300079
78,Colombia,100,50,30,20,0.500000,1.510000,0.820000,1756.070000,6,0,100,274.362269

In [7]:
save_team_profiles()

✅ team_strength_profiles.csv saved successfully

,team,matches_played,wins,draws,losses,win_pct,avg_goals_scored,avg_goals_conceded,avg_opponent_elo,elite_wins,world_cup_upsets,big_match_points,adjusted_strength
77,France,111,71,22,18,0.639640,2.081081,0.855856,1711.279279,22,4,262,429.673139
82,Spain,107,65,30,12,0.607477,2.317757,0.785047,1716.383178,14,0,175,407.683405
150,Belgium,105,66,19,20,0.628571,2.323810,0.819048,1655.895238,8,3,133,385.841936
90,Argentina,106,72,19,15,0.679245,1.990566,0.603774,1712.584906,7,1,129,379.101842
91,Japan,112,71,16,25,0.633929,2.276786,0.767857,1647.937500,5,2,94,372.465484
...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,Bhutan,28,4,2,22,0.142857,0.428571,2.857143,1500.000000,0,0,0,-58.206114
25,Liechtenstein,79,5,10,64,0.063291,0.341772,2.632911,1545.936709,0,0,0,-79.207517
160,Seychelles,50,2,13,35,0.040000,0.440000,2.880000,1508.000000,0,0,0,-82.316701
197,Anguilla,40,4,6,30,0.100000,0.500000,3.600000,1505.925000,0,0,0,-105.660781
216,San Marino,78,2,7,69,0.025641,0.269231,3.166667,1541.012821,0,0,0,-126.232676